jwt:
  secret: '[a-zA-Z0-9._]^+$AutoCase89797987forHaglerAndTeamNumeralsandOtherSymbol$'

server:
  port: 8081
  error:
    path: /error

spring:
  # datasource settings
  datasource:
    url: jdbc:mysql://localhost:3306/auto_case?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
  # jpa settings
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect